version: '3.7'

services:
  influxdb:
    image: influxdb:2.5.0
    container_name: influxdb
    ports:
      - 8086:8086
    restart: always
    volumes:
      - .influx-configs:/etc/influxdb2/influx-configs:rw
      - ./config.yml:/etc/influxdb2/config.yml:rw
      - /var/lib/influxdb:/var/lib/influxdb2:rw
